name: Bug Report
description: File a bug report.
title: "[MODNAME]: "
labels: ["bug", "unreviewed"]
assignees:
  - paulwrubel
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible to help me identify the issue quickly.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the mod are you using?
    validations:
      required: true
  - type: textarea
    id: smapi-logs
    attributes:
      label: SMAPI logs
      description: Please copy and paste any relevant log output or a link to the SMAPI log output on smapi.io
      render: shell
