name: Feature Request
description: Submit a feature request.
title: "[MODNAME]: "
labels: ["enhancement", "unreviewed"]
assignees:
  - paulwrubel
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible so I understand the request.
  - type: textarea
    id: description
    attributes:
      label: What would you like to see added?
    validations:
      required: true
